export { ReporterInfoPage } from './ReporterInfoPage';
export { ResultPage } from './ResultPage';
export { RatingPage } from './RatingPage';
export { default as ScanIdPage } from './ScanIdPage';
export { AliasPage } from './AliasPage';
export { WelcomePage } from './WelcomePage';
export { EvidenceRecapPage } from './EvidenceRecapPage';
export { TapeRevealPage } from './TapeRevealPage';
export { ArticleIntroPage } from './ArticleIntroPage';
export { ArticleDeathCausePage } from './ArticleDeathCausePage';
export { ArticleSuspectPage } from './ArticleSuspectPage';
export { ArticleMethodPage } from './ArticleMethodPage';
export { ArticleMotivePage } from './ArticleMotivePage'; 