export enum GameStage {
  START = 'START',
  INTRO = 'INTRO',
  EVIDENCE_SELECTION = 'EVIDENCE_SELECTION',
  WITNESS_SELECTION = 'WITNESS_SELECTION',
  SUSPECT_INTERVIEW = 'SUSPECT_INTERVIEW',
  ANGLE_GENERATION = 'ANGLE_GENERATION',
  REPORTER_INFO = 'REPORTER_INFO',
  RESULT = 'RESULT',
  RATING = 'RATING'
} 