export enum GameStage {
  START = 'start',
  SCAN_ID = 'scan_id',
  ALIAS = 'alias',
  WELCOME = 'welcome',
  EVIDENCE_RECAP = 'evidence_recap',
  TAPE_REVEAL = 'tape_reveal',
  SUSPECT_RECAP = 'suspect_recap',
  ARTICLE_INTRO = 'article_intro',
  ARTICLE_DEATH_CAUSE = 'article_death_cause',
  ARTICLE_SUSPECT = 'article_suspect',
  ARTICLE_METHOD = 'article_method',
  ARTICLE_MOTIVE = 'article_motive',
  ARTICLE_EVIDENCE = 'article_evidence',
  ARTICLE_WITNESS_QUOTES = 'article_witness_quotes',
  ARTICLE_INTERROGATION_FINDINGS = 'article_interrogation_findings',
  ANGLE_GENERATION = 'angle_generation',
  REPORTER_INFO = 'reporter_info',
  ARTICLE_STYLE = 'article_style',
  RESULT = 'result',
  RATING = 'rating'
} 